[package]
name = "screenshare"
version = "0.1.0"
edition = "2024"

[dependencies]
gio = "0.21.5"
glib = "0.21.5"
gstreamer = "0.24.4"
gstreamer-app = "0.24.4"
rand = "0.9.2"
raylib = { path = "../raylib" }
